import { noteSchema, type Note } from "@/lib/content/schemas";
import { parseContentCollection } from "@/lib/content/validation";

const demoNotes = [
  {
    id: "bergamot",
    name: "Bergamot",
    family: "citrus",
    shortDescription: "Bright citrus lift for the opening impression.",
    cloudinaryImageId: "hhs/notes/bergamot",
    accentColor: "#D9BC6A",
  },
  {
    id: "pink-pepper",
    name: "Pink Pepper",
    family: "spice",
    shortDescription: "A dry sparkle that keeps the first impression awake.",
    cloudinaryImageId: "hhs/notes/pink-pepper",
    accentColor: "#B08D3A",
  },
  {
    id: "oud",
    name: "Oud",
    family: "woody",
    shortDescription: "Resinous, smoky and grounded.",
    cloudinaryImageId: "hhs/notes/oud",
    accentColor: "#8A6C22",
  },
  {
    id: "rose",
    name: "Rose",
    family: "floral",
    shortDescription: "Soft floral depth without sweetness becoming loud.",
    cloudinaryImageId: "hhs/notes/rose",
    accentColor: "#7C4A45",
  },
  {
    id: "amber",
    name: "Amber",
    family: "warm",
    shortDescription: "A golden warmth that links the demonstration pair.",
    cloudinaryImageId: "hhs/notes/amber",
    accentColor: "#B08D3A",
  },
  {
    id: "musk",
    name: "Musk",
    family: "skin",
    shortDescription: "A quiet skin note that helps the scent linger.",
    cloudinaryImageId: "hhs/notes/musk",
    accentColor: "#F0E2B8",
  },
  {
    id: "lemon",
    name: "Lemon",
    family: "citrus",
    shortDescription: "Crisp, zesty citrus opening with vibrant energy.",
    cloudinaryImageId: "hhs/notes/lemon",
    accentColor: "#E8D84F",
  },
  {
    id: "apple",
    name: "Apple",
    family: "fruity",
    shortDescription: "Crisp and juicy green apple bringing modern freshness.",
    cloudinaryImageId: "hhs/notes/apple",
    accentColor: "#88B04B",
  },
  {
    id: "pineapple",
    name: "Pineapple",
    family: "fruity",
    shortDescription: "Tropical, sweet-tart fruitiness with vibrant radiance.",
    cloudinaryImageId: "hhs/notes/pineapple",
    accentColor: "#E5A93C",
  },
  {
    id: "blackcurrant",
    name: "Blackcurrant",
    family: "fruity",
    shortDescription: "Dark, tangy berry accord with rich depth.",
    cloudinaryImageId: "hhs/notes/blackcurrant",
    accentColor: "#582C4D",
  },
  {
    id: "cinnamon",
    name: "Cinnamon",
    family: "spice",
    shortDescription: "Warm, sweet aromatic spice evoking evening comfort.",
    cloudinaryImageId: "hhs/notes/cinnamon",
    accentColor: "#9E472A",
  },
  {
    id: "birch",
    name: "Birch",
    family: "woody",
    shortDescription: "Smoky, leathery wood character providing distinct masculinity.",
    cloudinaryImageId: "hhs/notes/birch",
    accentColor: "#4A3728",
  },
  {
    id: "jasmine",
    name: "Jasmine",
    family: "floral",
    shortDescription: "Intoxicating white floral heart adding smooth luxury.",
    cloudinaryImageId: "hhs/notes/jasmine",
    accentColor: "#EAE6DF",
  },
  {
    id: "orange-blossom",
    name: "Orange Blossom",
    family: "floral",
    shortDescription: "Luminous, honeyed floral note with a warm Mediterranean soul.",
    cloudinaryImageId: "hhs/notes/orange-blossom",
    accentColor: "#F4A261",
  },
  {
    id: "lavender",
    name: "Lavender",
    family: "aromatic",
    shortDescription: "Clean, calming French herbal accord providing timeless refinement.",
    cloudinaryImageId: "hhs/notes/lavender",
    accentColor: "#967BB6",
  },
  {
    id: "saffron",
    name: "Saffron",
    family: "spice",
    shortDescription: "Opulent golden spice adding bittersweet warmth and leather facets.",
    cloudinaryImageId: "hhs/notes/saffron",
    accentColor: "#C84B31",
  },
  {
    id: "praline",
    name: "Praline",
    family: "gourmand",
    shortDescription: "Caramelized nutty sweetness bringing decadent allure.",
    cloudinaryImageId: "hhs/notes/praline",
    accentColor: "#B5651D",
  },
  {
    id: "patchouli",
    name: "Patchouli",
    family: "earthy",
    shortDescription: "Rich, dark earthy woodiness that anchors the composition.",
    cloudinaryImageId: "hhs/notes/patchouli",
    accentColor: "#5C4033",
  },
  {
    id: "vanilla",
    name: "Vanilla",
    family: "sweet",
    shortDescription: "Creamy, sensual Madagascar vanilla with addictive warmth.",
    cloudinaryImageId: "hhs/notes/vanilla",
    accentColor: "#D4AF37",
  },
  {
    id: "tonka-bean",
    name: "Tonka Bean",
    family: "warm",
    shortDescription: "Almond-vanilla warmth with hints of coumarin and tobacco.",
    cloudinaryImageId: "hhs/notes/tonka-bean",
    accentColor: "#8D5B4C",
  },
  {
    id: "ambergris",
    name: "Ambergris",
    family: "skin",
    shortDescription: "Marine, salty-warm fixative giving incredible projection and endurance.",
    cloudinaryImageId: "hhs/notes/ambergris",
    accentColor: "#9C9A98",
  },
  {
    id: "cedarwood",
    name: "Cedarwood",
    family: "woody",
    shortDescription: "Dry, clean pencil-shaving cedar delivering structured elegance.",
    cloudinaryImageId: "hhs/notes/cedarwood",
    accentColor: "#7B3F00",
  },
  {
    id: "oakmoss",
    name: "Oakmoss",
    family: "mossy",
    shortDescription: "Forest-floor mossiness giving classic chypre depth.",
    cloudinaryImageId: "hhs/notes/oakmoss",
    accentColor: "#4B5320",
  },
  {
    id: "sweet-orange",
    name: "Sweet Orange",
    family: "citrus",
    shortDescription: "Juicy, sunshine-filled citrus burst full of delight.",
    cloudinaryImageId: "hhs/notes/sweet-orange",
    accentColor: "#FF7A00",
  },
  {
    id: "cardamom",
    name: "Cardamom",
    family: "spice",
    shortDescription: "Aromatic, resinous green spice with a warm herbal lift.",
    cloudinaryImageId: "hhs/notes/cardamom",
    accentColor: "#7B904B",
  },
] satisfies Note[];

export const notes = parseContentCollection(noteSchema, demoNotes, "notes");
